"""sdadsa

Revision ID: dce3a8e6acb8
Revises: 2bd5378be5bc
Create Date: 2024-02-28 16:03:27.334848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dce3a8e6acb8'
down_revision: Union[str, None] = '2bd5378be5bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('article_tag_tag_id_fkey', 'article_tag', type_='foreignkey')
    op.drop_constraint('article_tag_article_id_fkey', 'article_tag', type_='foreignkey')
    op.create_foreign_key(None, 'article_tag', 'articles', ['article_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'article_tag', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('articles_media_id_fkey', 'articles', type_='foreignkey')
    op.drop_constraint('articles_author_id_fkey', 'articles', type_='foreignkey')
    op.create_foreign_key(None, 'articles', 'media_files', ['media_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'articles', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('comments_author_id_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_article_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'articles', ['article_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_article_id_fkey', 'comments', 'articles', ['article_id'], ['id'])
    op.create_foreign_key('comments_author_id_fkey', 'comments', 'users', ['author_id'], ['id'])
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.create_foreign_key('articles_author_id_fkey', 'articles', 'users', ['author_id'], ['id'])
    op.create_foreign_key('articles_media_id_fkey', 'articles', 'media_files', ['media_id'], ['id'])
    op.drop_constraint(None, 'article_tag', type_='foreignkey')
    op.drop_constraint(None, 'article_tag', type_='foreignkey')
    op.create_foreign_key('article_tag_article_id_fkey', 'article_tag', 'articles', ['article_id'], ['id'])
    op.create_foreign_key('article_tag_tag_id_fkey', 'article_tag', 'tags', ['tag_id'], ['id'])
    # ### end Alembic commands ###
